name: Deploy to EC2 using Ansible

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: SSH and Deploy to EC2
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH key
      run: |
        echo "${{ secrets.EC2_PRIVATE_KEY }}" > key.pem
        chmod 600 key.pem

    - name: Run Ansible playbook
      run: |
        sudo apt-get update
        sudo apt-get install -y ansible
        echo "[web]" > hosts.ini
        echo "${{ secrets.EC2_PUBLIC_IP }} ansible_user=ubuntu ansible_ssh_private_key_file=key.pem" >> hosts.ini
        ansible-playbook -i hosts.ini docker-setup.yml
